steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'australia-southeast-2-docker.pkg.dev/helloworld-yuen/helloworldyuen-image', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'australia-southeast-2-docker.pkg.dev/helloworld-yuen/helloworldyuen-image']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'helloworld-yuen'
  - '--image'
  - 'gcr.io/helloworld-yuen/helloworld-yuen.:$COMMIT_SHA'
  - '--region'
  - 'australia-southeast-2'
images:
  - 'gcr.io/helloworld-yuen/helloworld-yuen.:$COMMIT_SHA'
options:
  logging: CLOUD_LOGGING_ONLY